# Generated by Django 6.0.1 on 2026-01-13 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('checklist', models.TextField(help_text='Escribe aquí las tareas')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus_activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.area')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_meses', models.IntegerField(default=1, help_text='Cada cuántos meses')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='mantenimiento.activo')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.plantillapm')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_ventana', models.DateField()),
                ('fecha_fin_ventana', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=15)),
                ('comentarios', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.planpm')),
            ],
        ),
    ]
