# Generated by Django 6.0.1 on 2026-01-13 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpm',
            name='fecha_proxima_ejecucion',
            field=models.DateField(default=django.utils.timezone.now, help_text='Selecciona cualquier día del mes que quieres empezar', verbose_name='Mes de inicio/próximo'),
            preserve_default=False,
        ),
    ]
