# Generated by Django 6.0.1 on 2026-01-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_planpm_fecha_proxima_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpm',
            name='fecha_proxima_ejecucion',
            field=models.DateField(blank=True, null=True, verbose_name='Mes de inicio'),
        ),
    ]
