# Generated by Django 6.0.1 on 2026-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_planpm_fecha_proxima_ejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
